# Hash tables(hashmap) are used to implement maps. The dict class is implemented with
# hash tables.
# They store data in an associateve manner.
# The keys of a dictionary are generated by a hashing function.
